"""
    SCIM API

    Janssen SCIM 2.0 server API. Developers can think of SCIM as a REST API with endpoints exposing CRUD functionality (create, update, retrieve and delete) for identity management resources such as users, groups, and fido devices.   # noqa: E501

    The version of the OpenAPI document: 5.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyscim
from pyscim.model.service_provider_config_response_bulk import ServiceProviderConfigResponseBulk


class TestServiceProviderConfigResponseBulk(unittest.TestCase):
    """ServiceProviderConfigResponseBulk unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServiceProviderConfigResponseBulk(self):
        """Test ServiceProviderConfigResponseBulk"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ServiceProviderConfigResponseBulk()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
