"""
    SCIM API

    Janssen SCIM 2.0 server API. Developers can think of SCIM as a REST API with endpoints exposing CRUD functionality (create, update, retrieve and delete) for identity management resources such as users, groups, and fido devices.   # noqa: E501

    The version of the OpenAPI document: 5.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyscim
from pyscim.model.basic_list_response import BasicListResponse
from pyscim.model.fido2_device_resource import Fido2DeviceResource
from pyscim.model.fido2_list_response_all_of import Fido2ListResponseAllOf
globals()['BasicListResponse'] = BasicListResponse
globals()['Fido2DeviceResource'] = Fido2DeviceResource
globals()['Fido2ListResponseAllOf'] = Fido2ListResponseAllOf
from pyscim.model.fido2_list_response import Fido2ListResponse


class TestFido2ListResponse(unittest.TestCase):
    """Fido2ListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFido2ListResponse(self):
        """Test Fido2ListResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Fido2ListResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
