"""
    SCIM API

    Janssen SCIM 2.0 server API. Developers can think of SCIM as a REST API with endpoints exposing CRUD functionality (create, update, retrieve and delete) for identity management resources such as users, groups, and fido devices.   # noqa: E501

    The version of the OpenAPI document: 5.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import pyscim
from pyscim.api.user_api import UserApi  # noqa: E501


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self):
        self.api = UserApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_user(self):
        """Test case for create_user

        """
        pass

    def test_delete_user_by_id(self):
        """Test case for delete_user_by_id

        """
        pass

    def test_get_user_by_id(self):
        """Test case for get_user_by_id

        """
        pass

    def test_get_users(self):
        """Test case for get_users

        """
        pass

    def test_patch_user_by_id(self):
        """Test case for patch_user_by_id

        """
        pass

    def test_search_user(self):
        """Test case for search_user

        """
        pass

    def test_update_user_by_id(self):
        """Test case for update_user_by_id

        """
        pass


if __name__ == '__main__':
    unittest.main()
