"""
    SCIM API

    Janssen SCIM 2.0 server API. Developers can think of SCIM as a REST API with endpoints exposing CRUD functionality (create, update, retrieve and delete) for identity management resources such as users, groups, and fido devices.   # noqa: E501

    The version of the OpenAPI document: 5.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import pyscim
from pyscim.api.global_search_api import GlobalSearchApi  # noqa: E501


class TestGlobalSearchApi(unittest.TestCase):
    """GlobalSearchApi unit test stubs"""

    def setUp(self):
        self.api = GlobalSearchApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_search_resources(self):
        """Test case for search_resources

        """
        pass


if __name__ == '__main__':
    unittest.main()
