"""
    SCIM API

    Janssen SCIM 2.0 server API. Developers can think of SCIM as a REST API with endpoints exposing CRUD functionality (create, update, retrieve and delete) for identity management resources such as users, groups, and fido devices.   # noqa: E501

    The version of the OpenAPI document: 5.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyscim
from pyscim.model.group_resource import GroupResource
globals()['GroupResource'] = GroupResource
from pyscim.model.group_list_response_all_of import GroupListResponseAllOf


class TestGroupListResponseAllOf(unittest.TestCase):
    """GroupListResponseAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGroupListResponseAllOf(self):
        """Test GroupListResponseAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GroupListResponseAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
