"""
    SCIM API

    Janssen SCIM 2.0 server API. Developers can think of SCIM as a REST API with endpoints exposing CRUD functionality (create, update, retrieve and delete) for identity management resources such as users, groups, and fido devices.   # noqa: E501

    The version of the OpenAPI document: 5.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyscim
from pyscim.model.resource_type_schema_extensions import ResourceTypeSchemaExtensions


class TestResourceTypeSchemaExtensions(unittest.TestCase):
    """ResourceTypeSchemaExtensions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResourceTypeSchemaExtensions(self):
        """Test ResourceTypeSchemaExtensions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ResourceTypeSchemaExtensions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
