"""
    SCIM API

    Janssen SCIM 2.0 server API. Developers can think of SCIM as a REST API with endpoints exposing CRUD functionality (create, update, retrieve and delete) for identity management resources such as users, groups, and fido devices.   # noqa: E501

    The version of the OpenAPI document: 5.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyscim
from pyscim.model.basic_list_response import BasicListResponse
from pyscim.model.fido_device_resource import FidoDeviceResource
from pyscim.model.fido_list_response_all_of import FidoListResponseAllOf

globals()["BasicListResponse"] = BasicListResponse
globals()["FidoDeviceResource"] = FidoDeviceResource
globals()["FidoListResponseAllOf"] = FidoListResponseAllOf
from pyscim.model.fido_list_response import FidoListResponse


class TestFidoListResponse(unittest.TestCase):
    """FidoListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFidoListResponse(self):
        """Test FidoListResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FidoListResponse()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
