"""
    SCIM API

    Janssen SCIM 2.0 server API. Developers can think of SCIM as a REST API with endpoints exposing CRUD functionality (create, update, retrieve and delete) for identity management resources such as users, groups, and fido devices.   # noqa: E501

    The version of the OpenAPI document: 5.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyscim
from pyscim.model.base_resource import BaseResource
from pyscim.model.group_resource_all_of import GroupResourceAllOf
from pyscim.model.member import Member
from pyscim.model.meta import Meta
globals()['BaseResource'] = BaseResource
globals()['GroupResourceAllOf'] = GroupResourceAllOf
globals()['Member'] = Member
globals()['Meta'] = Meta
from pyscim.model.group_resource import GroupResource


class TestGroupResource(unittest.TestCase):
    """GroupResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGroupResource(self):
        """Test GroupResource"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GroupResource()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
