"""
    SCIM API

    Janssen SCIM 2.0 server API. Developers can think of SCIM as a REST API with endpoints exposing CRUD functionality (create, update, retrieve and delete) for identity management resources such as users, groups, and fido devices.   # noqa: E501

    The version of the OpenAPI document: 5.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyscim
from pyscim.model.address import Address
from pyscim.model.email import Email
from pyscim.model.entitlement import Entitlement
from pyscim.model.fido2_device_resource import Fido2DeviceResource
from pyscim.model.fido_device_resource import FidoDeviceResource
from pyscim.model.group import Group
from pyscim.model.group_resource import GroupResource
from pyscim.model.instant_messaging_address import InstantMessagingAddress
from pyscim.model.member import Member
from pyscim.model.meta import Meta
from pyscim.model.name import Name
from pyscim.model.phone_number import PhoneNumber
from pyscim.model.photo import Photo
from pyscim.model.role import Role
from pyscim.model.user_resource import UserResource
from pyscim.model.x509_certificate import X509Certificate
globals()['Address'] = Address
globals()['Email'] = Email
globals()['Entitlement'] = Entitlement
globals()['Fido2DeviceResource'] = Fido2DeviceResource
globals()['FidoDeviceResource'] = FidoDeviceResource
globals()['Group'] = Group
globals()['GroupResource'] = GroupResource
globals()['InstantMessagingAddress'] = InstantMessagingAddress
globals()['Member'] = Member
globals()['Meta'] = Meta
globals()['Name'] = Name
globals()['PhoneNumber'] = PhoneNumber
globals()['Photo'] = Photo
globals()['Role'] = Role
globals()['UserResource'] = UserResource
globals()['X509Certificate'] = X509Certificate
from pyscim.model.generic_resource import GenericResource


class TestGenericResource(unittest.TestCase):
    """GenericResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGenericResource(self):
        """Test GenericResource"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GenericResource()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
