# flake8: noqa

"""
    SCIM API

    Janssen SCIM 2.0 server API. Developers can think of SCIM as a REST API with endpoints exposing CRUD functionality (create, update, retrieve and delete) for identity management resources such as users, groups, and fido devices.   # noqa: E501

    The version of the OpenAPI document: 5.0.0
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from pyscim.api_client import ApiClient

# import Configuration
from pyscim.configuration import Configuration

# import exceptions
from pyscim.exceptions import OpenApiException
from pyscim.exceptions import ApiAttributeError
from pyscim.exceptions import ApiTypeError
from pyscim.exceptions import ApiValueError
from pyscim.exceptions import ApiKeyError
from pyscim.exceptions import ApiException
